import { Character2 } from '../../models/character2';
import {
  IBaseEquipment,
  EquipmentType,
  CompoundOn,
} from '../../models/equipment';

const vmGroup1 = [1600, 2026];

export const matkPercent: IBaseEquipment[] = [
  // MATK +x% [2102001 - 2102100]
  {
    id: 2102001,
    name: `MATK +1%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      matkPercent: 0.01,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...vmGroup1],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2102002,
    name: `MATK +2%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      matkPercent: 0.02,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...vmGroup1],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2102003,
    name: `MATK +3%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      matkPercent: 0.03,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...vmGroup1],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2102004,
    name: `MATK +4%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      matkPercent: 0.04,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...vmGroup1],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2102005,
    name: `MATK +5%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      matkPercent: 0.05,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...vmGroup1],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2102006,
    name: `MATK +6%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      matkPercent: 0.06,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...vmGroup1],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2102007,
    name: `MATK +7%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      matkPercent: 0.07,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...vmGroup1],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2102008,
    name: `MATK +8%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      matkPercent: 0.08,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...vmGroup1],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2102009,
    name: `MATK +9%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      matkPercent: 0.09,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...vmGroup1],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2102010,
    name: `MATK +10%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      matkPercent: 0.1,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...vmGroup1],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
];
