import { Character2 } from '../../models/character2';
import {
  CompoundOn,
  EquipmentType,
  IBaseEquipment,
} from '../../models/equipment';

const vmGroup1 = [1600, 2026];
const vmGroup4 = [13328, 28605, 28706];

export const matkFlat: IBaseEquipment[] = [
  // MATK +x [2107001 - 2107200]
  {
    id: 2107001,
    name: `MATK +1`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 1,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107002,
    name: `MATK +2`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 2,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107003,
    name: `MATK +3`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 3,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107004,
    name: `MATK +4`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 4,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107005,
    name: `MATK +5`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 5,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107006,
    name: `MATK +6`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 6,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107007,
    name: `MATK +7`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 7,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107008,
    name: `MATK +8`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 8,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107009,
    name: `MATK +9`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 9,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107010,
    name: `MATK +10`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 1,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107011,
    name: `MATK +11`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 11,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107012,
    name: `MATK +12`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 12,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107013,
    name: `MATK +13`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 13,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107014,
    name: `MATK +14`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 14,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107015,
    name: `MATK +15`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 15,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107016,
    name: `MATK +16`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 16,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107017,
    name: `MATK +17`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 17,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107018,
    name: `MATK +18`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 18,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107019,
    name: `MATK +19`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 19,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107020,
    name: `MATK +20`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 2,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107021,
    name: `MATK +21`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 21,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107022,
    name: `MATK +22`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 22,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107023,
    name: `MATK +23`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 23,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107024,
    name: `MATK +24`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 24,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107025,
    name: `MATK +25`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 25,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107026,
    name: `MATK +26`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 26,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107027,
    name: `MATK +27`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 27,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107028,
    name: `MATK +28`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 28,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107029,
    name: `MATK +29`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 29,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107030,
    name: `MATK +30`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 3,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107031,
    name: `MATK +31`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 31,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107032,
    name: `MATK +32`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 32,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107033,
    name: `MATK +33`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 33,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107034,
    name: `MATK +34`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 34,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107035,
    name: `MATK +35`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 35,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107036,
    name: `MATK +36`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 36,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107037,
    name: `MATK +37`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 37,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107038,
    name: `MATK +38`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 38,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107039,
    name: `MATK +39`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 39,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107040,
    name: `MATK +40`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 4,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107041,
    name: `MATK +41`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 41,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107042,
    name: `MATK +42`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 42,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107043,
    name: `MATK +43`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 43,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107044,
    name: `MATK +44`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 44,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107045,
    name: `MATK +45`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 45,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107046,
    name: `MATK +46`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 46,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107047,
    name: `MATK +47`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 47,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107048,
    name: `MATK +48`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 48,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107049,
    name: `MATK +49`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 49,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2107050,
    name: `MATK +50`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      eMATK: 5,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
];
