import { Character2 } from '../../models/character2';
import {
  CompoundOn,
  EquipmentType,
  IBaseEquipment,
} from '../../models/equipment';
import {
  vmGroup1,
  vmGroup4,
  shadowsId,
  vmGroup5,
  temporalManteausId,
} from './equomentIds';

export const otherPercent: IBaseEquipment[] = [
  // Variable cast time +x% [2108001 - 2108100]
  {
    id: 2108001,
    name: `Variable cast time +1%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      vct: 0.01,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108002,
    name: `Variable cast time +2%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      vct: 0.02,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108003,
    name: `Variable cast time +3%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      vct: 0.03,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108004,
    name: `Variable cast time +4%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      vct: 0.04,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108005,
    name: `Variable cast time +5%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      vct: 0.05,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108006,
    name: `Variable cast time +6%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      vct: 0.06,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108007,
    name: `Variable cast time +7%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      vct: 0.07,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108008,
    name: `Variable cast time +8%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      vct: 0.08,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108009,
    name: `Variable cast time +9%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      vct: 0.09,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108010,
    name: `Variable cast time +10%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      vct: 0.1,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108011,
    name: `Variable cast time +11%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      vct: 0.11,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108012,
    name: `Variable cast time +12%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      vct: 0.12,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108013,
    name: `Variable cast time +13%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      vct: 0.13,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108014,
    name: `Variable cast time +14%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      vct: 0.14,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108015,
    name: `Variable cast time +15%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      vct: 0.15,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108016,
    name: `Variable cast time +16%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      vct: 0.16,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108017,
    name: `Variable cast time +17%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      vct: 0.17,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108018,
    name: `Variable cast time +18%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      vct: 0.18,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108019,
    name: `Variable cast time +19%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      vct: 0.19,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108020,
    name: `Variable cast time +20%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      vct: 0.2,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  // After cast delay +x% [2108201 - 2108300]
  {
    id: 2108201,
    name: `After cast delay +1%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      acd: 0.01,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108202,
    name: `After cast delay +2%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      acd: 0.02,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108203,
    name: `After cast delay +3%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      acd: 0.03,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108204,
    name: `After cast delay +4%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      acd: 0.04,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108205,
    name: `After cast delay +5%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      acd: 0.05,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108206,
    name: `After cast delay +6%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      acd: 0.06,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108207,
    name: `After cast delay +7%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      acd: 0.07,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108208,
    name: `After cast delay +8%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      acd: 0.08,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108209,
    name: `After cast delay +9%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      acd: 0.09,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108210,
    name: `After cast delay +10%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      acd: 0.1,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108211,
    name: `After cast delay +11%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      acd: 0.11,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108212,
    name: `After cast delay +12%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      acd: 0.12,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108213,
    name: `After cast delay +13%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      acd: 0.13,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108214,
    name: `After cast delay +14%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      acd: 0.14,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108215,
    name: `After cast delay +15%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      acd: 0.15,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108216,
    name: `After cast delay +16%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      acd: 0.16,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108217,
    name: `After cast delay +17%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      acd: 0.17,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108218,
    name: `After cast delay +18%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      acd: 0.18,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108219,
    name: `After cast delay +19%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      acd: 0.19,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108220,
    name: `After cast delay +20%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      acd: 0.2,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup1, ...vmGroup4],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  // ASPD +x% [2108501 - 2108600]
  {
    id: 2108501,
    name: `ASPD +1%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      aspd: 0.01,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...shadowsId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup4, ...vmGroup5],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108502,
    name: `ASPD +2%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      aspd: 0.02,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...shadowsId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup4, ...vmGroup5],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108503,
    name: `ASPD +3%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      aspd: 0.03,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...shadowsId, ...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup4, ...vmGroup5],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108504,
    name: `ASPD +4%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      aspd: 0.04,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...shadowsId, ...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup4, ...vmGroup5],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108505,
    name: `ASPD +5%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      aspd: 0.05,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...shadowsId, ...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup4, ...vmGroup5],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108506,
    name: `ASPD +6%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      aspd: 0.06,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108507,
    name: `ASPD +7%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      aspd: 0.07,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108508,
    name: `ASPD +8%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      aspd: 0.08,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108509,
    name: `ASPD +9%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      aspd: 0.09,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108510,
    name: `ASPD +10%`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      aspd: 0.1,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
];
