import { Character2 } from '../../models/character2';
import {
  IBaseEquipment,
  EquipmentType,
  CompoundOn,
} from '../../models/equipment';
import {
  shadowsId,
  temporalManteausId,
  vmGroup2,
  vmGroup3,
  vmGroup4,
  vmGroup5,
} from './equomentIds';

export const otherFlat: IBaseEquipment[] = [
  // ASPD +x [2108601 - 2108700]
  {
    id: 2108601,
    name: `ASPD + 1`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      aspdFlat: 1,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...shadowsId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup2, ...vmGroup3, ...vmGroup4, ...vmGroup5],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108602,
    name: `ASPD + 2`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      aspdFlat: 2,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup2, ...vmGroup3, ...vmGroup4, ...vmGroup5],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108603,
    name: `ASPD + 3`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      aspdFlat: 3,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup2, ...vmGroup3, ...vmGroup4, ...vmGroup5],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108604,
    name: `ASPD + 4`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      aspdFlat: 4,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup2, ...vmGroup3, ...vmGroup4, ...vmGroup5],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108605,
    name: `ASPD + 5`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      aspdFlat: 5,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup2, ...vmGroup3, ...vmGroup4, ...vmGroup5],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  // CRIT +x [2108701 - 2108800]
  {
    id: 2108701,
    name: `CRIT + 1`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      criRate: 1,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...shadowsId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup2, ...vmGroup3, ...vmGroup5],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108702,
    name: `CRIT + 2`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      criRate: 2,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...shadowsId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup2, ...vmGroup3, ...vmGroup5],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108703,
    name: `CRIT + 3`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      criRate: 3,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...shadowsId, ...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup2, ...vmGroup3, ...vmGroup5],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108704,
    name: `CRIT + 4`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      criRate: 4,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...shadowsId, ...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup2, ...vmGroup3, ...vmGroup5],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108705,
    name: `CRIT + 5`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      criRate: 5,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...shadowsId, ...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup2, ...vmGroup3, ...vmGroup5],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108706,
    name: `CRIT + 6`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      criRate: 6,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup2, ...vmGroup3, ...vmGroup5],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108707,
    name: `CRIT + 7`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      criRate: 7,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup2, ...vmGroup3, ...vmGroup5],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108708,
    name: `CRIT + 8`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      criRate: 8,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup2, ...vmGroup3, ...vmGroup5],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108709,
    name: `CRIT + 9`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      criRate: 9,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup2, ...vmGroup3, ...vmGroup5],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108710,
    name: `CRIT + 10`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      criRate: 10,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [...temporalManteausId],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup2, ...vmGroup3, ...vmGroup5],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108711,
    name: `CRIT + 11`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      criRate: 11,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup2, ...vmGroup3, ...vmGroup5],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108712,
    name: `CRIT + 12`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      criRate: 12,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup2, ...vmGroup3, ...vmGroup5],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108713,
    name: `CRIT + 13`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      criRate: 13,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup2, ...vmGroup3, ...vmGroup5],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108714,
    name: `CRIT + 14`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      criRate: 14,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup2, ...vmGroup3, ...vmGroup5],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108715,
    name: `CRIT + 15`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      criRate: 15,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup2, ...vmGroup3, ...vmGroup5],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108716,
    name: `CRIT + 16`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      criRate: 16,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup2, ...vmGroup3, ...vmGroup5],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108717,
    name: `CRIT + 17`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      criRate: 17,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup2, ...vmGroup3, ...vmGroup5],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108718,
    name: `CRIT + 18`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      criRate: 18,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup2, ...vmGroup3, ...vmGroup5],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108719,
    name: `CRIT + 19`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      criRate: 19,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup2, ...vmGroup3, ...vmGroup5],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
  {
    id: 2108720,
    name: `CRIT + 20`,
    type: EquipmentType.CARD,
    subType: null,
    location: null,
    compoundOn: CompoundOn.ENCHANT,
    baseDef: 0,
    baseATK: 0,
    level: 1,
    equipUpgradeValue: 0,
    str: 0,
    agi: 0,
    vit: 0,
    int: 0,
    dex: 0,
    luk: 0,
    additionAtk: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    additionDef: {
      size: 0,
      element: 0,
      race: 0,
      class: 0,
    },
    options: {
      criRate: 20,
    },
    eATK: 0,
    cATK: 0,
    criticalPercent: 0,
    penetrationPercent: 0,
    canSelectOnOption_1: {
      actives: [],
    },
    canSelectOnOption_2: {
      actives: [],
    },
    canSelectOnOption_3: {
      actives: [...vmGroup2, ...vmGroup3, ...vmGroup5],
    },
    script: (character: Character2, _this: IBaseEquipment): void => {},
  },
];
