import { equipments as Equipments } from './dbs/equipments';
import { specialEquipments as SpecialEquipments } from './dbs/special-equipments';
import { buffSkills as BuffSkills } from './dbs/buffSkills';
import { atkSkills as AtkSkills } from './dbs/atkSkills';
import { potionItems as PotionItems } from './dbs/potion';
import { classShadowSkill as ClassShadowSkill } from './dbs/class-shadow-skill';
import { allOptions as allOption } from './dbs/option/options';
import { cards } from './dbs/general-equipments/cards';
import { enchants } from './dbs/enchants';

export const equipments = Equipments;
export const specialEquipments = SpecialEquipments;
export const allEquipments = [...Equipments, ...SpecialEquipments];
export const version = require('../package.json').version;
export const buffSkills = BuffSkills;
export const atkSkills = AtkSkills;
export const potionItems = PotionItems;
export const classShadowSkill = ClassShadowSkill;
export const allOptions = allOption;
export const allCards = [...cards, ...enchants];
